name: Android CI with APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [17]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Change wrapper permissions
      run: chmod +x ./gradlew

    - name: Validate Gradle wrapper
      run: ./gradlew --version

    - name: Build Debug APK
      run: |
        ./gradlew assembleDebug --no-daemon --stacktrace
        echo "=== APK files created ==="
        find . -name "*.apk" -type f

    - name: List build outputs
      run: |
        echo "=== Build outputs structure ==="
        find app/build -name "*.apk" | head -10
        echo "=== Full app/build structure ==="
        ls -la app/build/outputs/ || echo "No outputs directory"
        ls -la app/build/outputs/apk/ || echo "No apk directory"

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: secure-p2p-chat-apk
        path: |
          app/build/outputs/apk/debug/*.apk
          app/build/outputs/apk/release/*.apk
        retention-days: 7
      if: success()

    - name: Build tests
      run: ./gradlew testDebugUnitTest --no-daemon

  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build Release APK
      run: |
        ./gradlew assembleRelease --no-daemon --stacktrace
        mkdir -p release-apk
        cp app/build/outputs/apk/release/app-release-unsigned.apk release-apk/

    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: secure-p2p-chat-release
        path: release-apk/*.apk
        retention-days: 30
