name: Android CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Validate project structure
      run: |
        echo "Checking project files..."
        ls -la
        echo "Checking app directory..."
        ls -la app/ || echo "No app directory"
        echo "Checking gradle files..."
        ls -la gradle/ || echo "No gradle directory"
        
    - name: Try to build with Gradle
      run: |
        if [ -f "./gradlew" ]; then
          chmod +x ./gradlew
          ./gradlew tasks --no-daemon || echo "Gradle tasks failed"
        else
          echo "gradlew file not found, using system gradle"
          gradle tasks --no-daemon || echo "System gradle failed"
        fi
